import Head from 'next/head'
import LoginPage from '../src/views/login/LoginPage'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="assets/images/favicon.png" />
      </Head>
      <main>
        <LoginPage />
      </main>
    </div>
  )
}
